# SPDX-FileCopyrightText: 2022 Alexander Dahl <alex@netz39.de>
# SPDX-License-Identifier: MIT
---
# main tasks file for telegraf-docker-in-docker

- name: Run all tasks for role telegraf-docker-in-docker
  when: tdid_arch_is_supported
  ansible.builtin.include_tasks:
    file: tdid.yml

- name: Inform user why tasks for role telegraf-docker-in-docker were skipped
  ansible.builtin.debug:
    msg: "Skipped because for {{ ansible_architecture }} there is no docker image!"
  when: not tdid_arch_is_supported
