# SPDX-FileCopyrightText: 2022 Alexander Dahl
# SPDX-License-Identifier: MIT
---
# handlers file for telegraf-docker-in-docker
- name: Restart telegraf docker_input_agent
  docker_container:
    name: telegraf_docker_input_agent
    state: started
    restart: yes
